[workspace]
members = ["file", "magic", "lazy-cache", "magic-embed"]
resolver = "3"

[workspace.package]
authors = ["Quentin JÉRÔME <quentin.jerome@circl.lu>"]
repository = "https://github.com/qjerome/magic-rs/"
license = "GPL-3.0"
