[workspace]
members = ["wiza", "pure-magic", "lazy-cache", "magic-embed", "magic-db"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.88.0"
authors = ["Quentin JÉRÔME <quentin.jerome@circl.lu>"]
repository = "https://github.com/qjerome/magic-rs/"
license = "GPL-3.0"
