[package]
name = "pymagic-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pymagic"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
magic-db = { path = "../magic-db", version = "0.1" }
magic-rs = { path = "../magic", version = "0.1" }
