[package]
name = "lazy-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
lru-st = "0.3.0"

[dev-dependencies]
criterion = "0.7.0"
rand = "0.9.2"

[[bench]]
name = "lazy_cache_benchmark"
harness = false
